import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";

import { Toaster } from "@/components/ui/sonner";

const tatsanaChong = localFont({
  src: [
    {
      path: "../fonts/TATSANA-CHON-LIG.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/TATSANA-CHON-REG.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/TATSANA-CHON-BLD.woff",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-tatsana-chong",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={tatsanaChong.className}>
        <SpeedInsights />
        <Analytics />
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
